module.exports = [
    { name: 'gast', elements: ['light', 'water', 'earth'] },
    { name: 'harvester', elements: ['fire', 'basic', 'light'] },
    { name: 'demon', elements: ['basic', 'fire', 'light'] },
    { name: 'minotaur', elements: ['earth', 'fire'] },
    { name: 'marina', elements: ['water', 'basic'] },
    { name: 'sandy', elements: ['light', 'dark'] },
    { name: 'goblin', elements: ['fire'] },
    { name: 'slime', elements: ['dark', 'fire'] },
    { name: 'shadow', elements: ['dark', 'basic'] },
    { name: 'commander', elements: ['basic', 'dark'] },
    { name: 'erina', elements: ['earth', 'light'] },
    { name: 'panda', elements: ['earth', 'basic'] },
    { name: 'fairy', elements: ['water', 'light'] },
    { name: 'viper', elements: ['light', 'dark'] },
    { name: 'elphaba', elements: ['dark', 'basic'] },
    { name: 'worm', elements: ['earth'] },
    { name: 'garam', elements: ['light', 'water'] },
    { name: 'director', elements: ['light', 'water', 'dark'] },
    { name: 'duncan', elements: ['basic', 'dark', 'earth'] },
    { name: 'knight', elements: ['earth', 'dark', 'fire'] },
    { name: 'terrorist', elements: ['earth', 'water', 'light'] },
    { name: 'carmen', elements: ['water'] },
    { name: 'jerry', elements: ['dark'] },
];